import type { Metadata } from "next";
import { Amiri, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "./components/Navber";
import Topbar from "./components/Topbar";





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const amiri = Amiri({
  variable: "--font-arabic",
  subsets: ["arabic"],
  weight: "400", // Or add multiple weights like: ["400", "700"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
     <body className={`${geistSans.variable} ${geistMono.variable} ${amiri.variable} antialiased`}>

        <main className="grid grid-cols-26 ">
          <div className="">
            <Navber />
          </div>
          <div className="col-span-25">
            <Topbar />

            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
